version: '3'

services:

  consul:
    image: consul:1.1.0
    hostname: localhost
    networks:
      - overlay
    ports:
      - 8500:8500
#  mysql:
#    image: library/mysql:5.7
#    command: "--innodb_use_native_aio=0"
#    container_name: "mysql"
#    env_file:
#      - db-mysql/db_mysql.env
#    restart: "no"
#    ports:
#      - 3306:3306
#    volumes:
#      - ./db-mysql/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
#      - ./db-mysql/data:/var/lib/mysql
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#      - COMPOSE_CONVERT_WINDOWS_PATHS=1
#    networks:
#      - overlay

  admin:
    restart: always
    image: "quay.io/basis-company/tarantool-admin"
    ports:
      - 8888:80
    networks:
      - overlay

  tarantool:
    image: "tarantool/tarantool:2.1"
    container_name: "tarantool"
#    command: sh -c "sleep 15 && tarantool /opt/tarantool/init.lua"
    ports:
      - 3301:3301
    restart: always
    healthcheck:
      test: tarantool_is_up
      interval: 60s
      timeout: 15s
      retries: 10
    volumes:
      - ./db-tarantool/conf/init.lua:/opt/tarantool/init.lua
      - ./db-tarantool/conf/config.yml:/etc/default/tarantool/config.yml
    #      - ./db-tarantool/data:/var/lib/tarantool
    environment:
      - TARANTOOL_USER_NAME=admin
      - TARANTOOL_USER_PASSWORD=admin
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    networks:
      - overlay


networks:
  overlay: